---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: traefik
      version: 16.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: ${releaseNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: ${releaseNamespace}