---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nifi
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: nifikop
      sourceRef:
        kind: HelmRepository
        name: nifikop
        namespace: ${releaseNamespace} 
      version: v0.14.0-release
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  releaseName: nifikop
  valuesFrom:
    - kind: ConfigMap
      name: nifikop-defaults
  targetNamespace: ${releaseNamespace}