---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nifi
  namespace: nifi
spec:
  chart:
    spec:
      chart: ./chart/nifikop-0.14.0.tgz
      version: 0.14.0
      sourceRef:
        kind: GitRepository
        name: swiftsuretech
        namespace: nifi
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: nifi
  valuesFrom:
  - kind: ConfigMap
    name: nifikop-defaults