---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nifi
  namespace: nifi
spec:
  chart:
    spec:
      chart: nifikop
      version: 0.14.2
      sourceRef:
        kind: HelmRepository
        name: swiftsuretech
        namespace: nifi
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  valuesFrom:
   - kind: ConfigMap
     name: nifikop-defaults
  targetNamespace: nifi