---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zookeeper
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: ./chart/zookeeper-10.2.0.tgz
      version: 10.2.0
      sourceRef:
        kind: GitRepository
        name: swiftsuretech
        namespace: ${releaseNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: ${releaseNamespace}
  valuesFrom:
  - kind: ConfigMap
    name: zookeeper-defaults