---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zookeeper
  namespace: nifi-h28s4
spec:
  chart:
    spec:
      chart: zookeeper
      version: 10.2.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: nifi-h28s4
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: nifi-h28s4
  valuesFrom:
  - kind: ConfigMap
    name: zookeeper-defaults