---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: registry
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: nifi-registry
      sourceRef:
        kind: HelmRepository
        name: registry
        namespace: ${releaseNamespace}
      version: 1.1.0
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  releaseName: nifi-registry
  valuesFrom:
    - kind: ConfigMap
      name: registry-defaults
  targetNamespace: ${releaseNamespace}