---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: streamlit
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: ./streamlit-app/deploy
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: streamlit
        namespace: ${releaseNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: ${releaseNamespace}
  valuesFrom:
  - kind: ConfigMap
    name: nifikop-defaults