apiVersion: v1
kind: ConfigMap
metadata:
  name: es-mapping
data:
  endpoint: |-
    http://elastic-es-default:9200/newsitems
  header: |-
    kbn-xsrf:reporting
  content-type: |-
    Content-Type:application/json
  credentials: |-
    elastic:elastic
  payload: |-
    {
      "properties": {
        "ctime": {
          "type": "date",
          "format": "EEE MMM dd HH:mm:ss z YYYY"
        },
        "domain": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "language": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "seendate": {
          "type": "date",
          "format": "basic_date_time_no_millis"
        },
        "socialimage": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "sourcecountry": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "title": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "url": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "url_mobile": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        }
      }
    }