kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: data-catalog-cluster
rules:
- apiGroups: ["rbac.authorization.k8s.io", "admissionregistration.k8s.io", "apiextensions.k8s.io", "policy", "storage.k8s.io", "ceph.rook.io"]
  resources: ["clusterroles", "clusterrolebindings", "validatingwebhookconfigurations", "customresourcedefinitions", "rolebindings", "podsecuritypolicies", "storageclasses", "cephclusters"]
  verbs:
  - "*"
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: data-catalog-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: data-catalog-cluster
subjects:
- kind: ServiceAccount
  name: ${releaseNamespace}
  namespace: ${releaseNamespace}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: data-catalog
  namespace: ${releaseNamespace}
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: data-catalog
  namespace: ${releaseNamespace}
subjects:
  - kind: ServiceAccount
    name: ${releaseNamespace}
    namespace: ${releaseNamespace}
  - kind: ServiceAccount
    name: nifikop
    namespace: ${releaseNamespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: data-catalog