---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook
  namespace: rook-ceph
spec:
  chart:
    spec:
      chart: rook-ceph
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: rook
        namespace: ${releaseNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: rook-ceph