---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: rook-ceph-cluster
      version: 1.10.2
      sourceRef:
        kind: HelmRepository
        name: rook
        namespace: ${releaseNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: ${releaseNamespace}
  valuesFrom:
    - kind: ConfigMap
      name: rook-cluster-defaults