---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: nonsuch
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: swiftsure
        namespace: ${releaseNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: ${releaseNamespace}