---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kowl
  namespace: data-project
spec:
  chart:
    spec:
      chart: kowl
      sourceRef:
        kind: HelmRepository
        name: kowl
        namespace: data-project
      version: 2.3.1
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  valuesFrom:
    - kind: ConfigMap
      name: kowl
  targetNamespace: data-project