kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: data-catalog-cluster
  labels:     
  {{- include "data-catalog.labels" . | nindent 4 }}
rules:
- apiGroups: ["rbac.authorization.k8s.io", "admissionregistration.k8s.io", "apiextensions.k8s.io", "policy", "storage.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings", "validatingwebhookconfigurations", "customresourcedefinitions", "podsecuritypolicies", "storageclasses"]
  verbs:
  - "*"
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: data-catalog-cluster
  labels:     
  {{- include "data-catalog.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: data-catalog-cluster
subjects:
- kind: ServiceAccount
  name: {{.Release.Namespace}}
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: data-catalog
  namespace: {{.Release.Namespace}}
  labels:
  {{- include "data-catalog.labels" . | nindent 4 }}
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: data-catalog
  labels:     
  {{- include "data-catalog.labels" . | nindent 4 }}
  namespace: {{.Release.Namespace}}
subjects:
  - kind: ServiceAccount
    name: {{.Release.Namespace}}
    namespace: {{.Release.Namespace}}
  - kind: ServiceAccount
    name: nifikop
    namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: data-catalog