---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefixes-minio
  labels:     
    {{- include "data-catalog.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
    - /minio
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: kommander-traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    # traefik.ingress.kubernetes.io/router.middlewares: kommander-stripprefixes-minio@kubernetescrd,kommander-forwardauth@kubernetescrd
  labels:     
    {{- include "data-catalog.labels" . | nindent 4 }}
  name: minio-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: nifi-minio-tennant
            port:
              number: 9001
        path: /minio
        pathType: Prefix