---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefixes-rook
  namespace: kommander
  labels:     
    {{- include "data-catalog.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
    - /rook
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: kommander-traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: kommander-stripprefixes-rook@kubernetescrd #kommander-forwardauth@kubernetescrd
  labels:     
    {{- include "data-catalog.labels" . | nindent 4 }}
  name: rook-ingress
  namespace: rook-ceph
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: rook-ceph-mgr-dashboard
            port:
              number: 8443
        path: /ceph
        pathType: Prefix