---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-ui
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: kafka-ui
      sourceRef:
        kind: HelmRepository
        name: provectus
        namespace: ${releaseNamespace}
      version: 0.4.3
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  releaseName: kafka-ui
  valuesFrom:
    - kind: ConfigMap
      name: kafka-ui
  targetNamespace: ${releaseNamespace}