---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-operator
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: kafka-operator
      sourceRef:
        kind: HelmRepository
        name: banzaicloud
        namespace: ${releaseNamespace}
      version: 0.21.2
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  releaseName: kafka-operator
  valuesFrom:
    - kind: ConfigMap
      name: kafka-defaults
  targetNamespace: ${releaseNamespace}