---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-tennant
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: tenant
      version: 4.5.1
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: ${releaseNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: ${releaseNamespace}
  valuesFrom:
    - kind: ConfigMap
      name: minio-tenant-defaults