---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nifikop
  namespace: ${releaseNamespace}
spec:
  interval: 1m
  timeout: 1m
  url: "${helmMirrorURL:=https://github.com/orgs/konpyutaika/packages/container/package/helm-charts/nifikop}"