apiVersion: nifi.konpyutaika.com/v1alpha1
kind: NifiCluster
metadata:
  name: nifi-demo
spec:
  service:
    headlessEnabled: true
    labels:
      cluster-name: nifi-demo
  zkAddress: zookeeper-nifi:2181
  zkPath: /nifi-demo
  externalServices:
    - metadata:
        labels:
          cluster-name: driver-nifi-demo
      name: driver-ip
      spec:
        portConfigs:
          - internalListenerName: http
            port: 8080
        type: ClusterIP
  clusterImage: "apache/nifi:1.15.3"
  initContainerImage: 'busybox:1.34.0'
  oneNifiNodePerNode: true
  readOnlyConfig:
    nifiProperties:
      overrideConfigs: |
        nifi.sensitive.props.key=thisIsABadSensitiveKeyPassword
  pod:
    labels:
      cluster-name: nifi-demo
  nodeConfigGroups:
    default_group:
      imagePullPolicy: IfNotPresent
      isNode: true
      serviceAccountName: default
      storageConfigs:
        - mountPath: "/opt/nifi/nifi-current/logs"
          name: logs
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "ebs-sc"
            resources:
              requests:
                storage: 100Gi
      resourcesRequirements:
        limits:
          cpu: "2"
          memory: 8Gi
        requests:
          cpu: "2"
          memory: 8Gi
  nodes:
    - id: 1
      nodeConfigGroup: "default_group"
    - id: 2
      nodeConfigGroup: "default_group"
    - id: 3
      nodeConfigGroup: "default_group"
  propagateLabels: true
  nifiClusterTaskSpec:
    retryDurationMinutes: 10
  listenersConfig:
    internalListeners:
      - containerPort: 8080
        type: http
        name: http
      - containerPort: 6007
        type: cluster
        name: cluster
      - containerPort: 10000
        type: s2s
        name: s2s
      - containerPort: 9090
        type: prometheus
        name: prometheus
      - containerPort: 6342
        type: load-balance
        name: load-balance
