apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: nifikop
  namespace: ${releaseNamespace}
spec:
  interval: 1m
  url: "${helmMirrorURL:=https://github.com/konpyutaika/nifikop}"
  ref:
    branch: master