apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: streamlit
  namespace: ${releaseNamespace}
spec:
  interval: 1m
  url: "${helmMirrorURL:=https://github.com/swiftsuretech/nifi_project}"
  ref:
    branch: master