---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: swiftsure
  namespace: ${workspaceNamespace}
  labels:
    kommander.d2iq.io/dkp-airgapped: supported
spec:
  url: "${helmMirrorURL:=https://swiftsuretech.github.io/streamlit-helm/}"
  interval: 5m