---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: swiftsure
  namespace: ${workspaceNamespace}
  labels:
    kommander.d2iq.io/dkp-airgapped: unsupported
spec:
  url: "${helmMirrorURL:=https://swiftsuretech.github.io/dkp_big_data_catalog/}"
  interval: 5m