---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: swiftsuretech
  namespace: ${releaseNamespace}
spec:
  interval: 1m
  timeout: 1m
  url:  "${helmMirrorURL:=https://swiftsuretech.github.io/helm-chart/charts}"