---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: proxy
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - services
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: proxy
subjects:
- kind: ServiceAccount
  name: proxy
---
apiVersion: v1
kind: Pod
metadata:
  name: sidecar-proxy
spec:
  serviceAccountName: proxy
  containers:
  - name: alpine
    image: alpine
    resources:
      requests:
        memory: "200Mi"
        cpu: "200m"
      limits:
        memory: "500Mi"
        cpu: "500m"
    command: ["sh", "-c", "apk add curl jq && sleep 4800"]
    env:
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: SVC_EP
        value: localhost:8080/api/v1/namespaces
  - name: sidecar
    image: bitnami/kubectl
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "200Mi"
        cpu: "200m"
    command: ["sh", "-c", "kubectl proxy --port=8080"]
    ports:
    - containerPort: 8080